plugins {
    id 'java'
    id "org.jetbrains.kotlin.jvm" version "1.9.0"
}

group 'com.warren'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    google()
    maven {
        url = uri("https://repo.powbot.org/releases")
    }
}

dependencies {
    implementation project(':powbot-bt')
    implementation('org.powbot:client-sdk:3+') // Can replace with `implementation('org.powbot:client-sdk:3+')` where + tries to pull the latest version
    implementation('org.powbot:client-sdk-loader:3+') // Can replace with `implementation('org.powbot:client-sdk-loader:3+')` where + tries to pull the latest version
    implementation('com.google.guava:guava:31.1-jre') // needed for @Subscribe annotations / event bus  
    implementation('com.fasterxml.jackson.core:jackson-core:2.13.0')
    implementation('org.slf4j:slf4j-api:2.0.9')
}